### ISSUE TITLE
Ошибки компиляции стратегий

### ISSUE THREAD

**Issue by Dovgalyuk** [Dovgalyuk/AIBattle#7]
В случае, когда пользователь загружает программу с ошибкой, он не получает никакого сообщения кроме "compilation error".
Нужно это исправить, чтобы показывался лог компиляции. Можно сохранять лог всегда, даже для успешной компиляции.

**Comment by TsarN** [comment]
А ошибки компиляции в stderr пишется?

**Comment by Dovgalyuk** [comment]
Вроде бы обычно туда.
